version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: malo_django_local
    command: >
      sh -c "
      echo 'Esperando pelo banco de dados...' &&
      /espera.sh db 3306 &&
      echo 'Banco de dados disponível, iniciando Django...' &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./malo:/app
      - ./.env:/app/.env  
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: malo_db_local
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:  
      - .env
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
