# Generated by Django 5.1.4 on 2024-12-30 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Garcom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=120, verbose_name='Cargo')),
                ('salario', models.FloatField(verbose_name='Salário')),
                ('login', models.CharField(max_length=120, verbose_name='Login')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ingrediente')),
                ('exp_date', models.DateField(verbose_name='Data de validade')),
                ('quantity', models.FloatField(verbose_name='Quantidade')),
                ('measure_unit', models.CharField(max_length=10, verbose_name='Unidade de medida')),
                ('price', models.FloatField(verbose_name='Preço de compra(total)')),
                ('obs', models.TextField(blank=True, verbose_name='Observação')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='nome')),
                ('exp_employees', models.FloatField(verbose_name='Despesas funcionarios')),
                ('tips', models.FloatField(verbose_name='servico')),
                ('billing', models.FloatField(verbose_name='faturamento')),
                ('feedstock', models.FloatField(verbose_name='insumos')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('descricao', models.CharField(default='Mesa', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome do prato')),
                ('price', models.FloatField(verbose_name='Preço de venda')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Malo_App.category')),
            ],
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Quantidade')),
                ('measure_unit', models.CharField(max_length=10, verbose_name='Unidade de medida')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Malo_App.dish')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Malo_App.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('total_price_local', models.FloatField(default=0)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Malo_App.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Malo_App.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Malo_App.order')),
            ],
        ),
    ]
