name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for GCP
        run: |
          gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -f Dockerfile.remote -t LOCATION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/django-app:latest .
          docker push LOCATION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/django-app:latest

      - name: Deploy to GCP VM via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          port: 22
          script: |
            docker pull LOCATION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/django-app:latest
            docker-compose -f docker-compose.remote.yml up -d
