name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run SAST with Bearer
        uses: bearer/bearer-action@v2

  
