name: Docker Build Test

on:
  push:
    branches:
      - main  
  pull_request:  
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Export environment variables
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env

      - name: Build Docker image
        run: |
          docker build \
            --file Dockerfile \
            --tag your-docker-image-name:latest \
            .

      - name: Run container for testing
        run: |
          docker run --rm -d \
            --env-file .env \
            -p 8000:8000 \
            --name test_container \
            your-docker-image-name:latest
          sleep 10  
          curl --fail http://localhost:8000 || (echo "Failed to connect to the application" && exit 1)

      - name: Stop and remove test container
        if: success()
        run: |
          docker stop test_container
